### ISSUE TITLE
Add topics below project description

### ISSUE THREAD

**Issue by martinmoene** [MayaPosch/NymphCast#1]
Adding topics below the project description line may help project discovery (`Manage Topics`).

For example, and among others: `audio audio-player audio-streaming video video-player video-streaming`

**Comment by MayaPosch** [comment]
I have added those and some more topics. Feel free to suggest more topics :)

**Comment by martinmoene** [comment]
Perhaps [angelscript](https://github.com/search?q=%23angelscript), [`casting`](https://github.com/search?q=%23casting)

**Comment by MayaPosch** [comment]
Added a few more, can leave this issue open for more ideas if necessary :)
