### ISSUE TITLE
Allow dynamic linking of the SDK

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphCast#12]
Linux Distributions don't like statically compiled packages. It forces rebuilds of all packages when the static library gets updated even when the ABI hasn't changed, the package sizes get bigger, etc. Currently libnymphcast gets compiled as a static library (`.a`), but it would be great if it could be linked too dynamically (as a `.so` file).

**Comment by MayaPosch** [comment]
Feature has been implemented, with an `.so` file produced in addition to the current `.a`. Please check that it works for you.

**Comment by PureTryOut** [comment]
Works, thanks!
