### ISSUE TITLE
Allow building player with non-installed client lib

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphCast#21]
Currently to package the demo player on Alpine Linux, I have it as a separate package which depends on `nymphcast-dev`. I have to do this because compilation of the player requires the SDK to be installed, but this is not yet the case when building the package. It would be good if we can somehow point the players Qmake script to the compiled sources in `src/client_lib`, so we can keep the packaging in a single package without the need to keep 2 packages in sync with each other.

Since the client is a separate thing anyway, shouldn't it be split into it's own repository? This way it would have it's own separate Git log, issue tracker, MR's, and packaging it separately would make more sense automatically.

**Comment by MayaPosch** [comment]
Splitting the NymphCast Player off into its own repository isn't a bad idea.

What about splitting the server and client SDK as well?

**Comment by PureTryOut** [comment]
Yeah sure, that's probably even better! They can have their own versioning too if you want that then.

**Comment by PureTryOut** [comment]
This has been fixed by moving libnymphcast to it's own repository as proposed in #47.
