### ISSUE TITLE
Add Sync broadcast for steteo amplified speakers

### ISSUE THREAD

**Issue by GiambaFr** [MayaPosch/NymphCast#23]
Broadcast from one emeter to multiple receivers for Sync steteo playing

**Comment by MayaPosch** [comment]
Hello, and thank for that feature suggestion! :)

Synchronised playback is a feature that has been planned for the v0.2 release. This will be the next development version after the upcoming v0.1 release.

**Comment by PureTryOut** [comment]
You could look into using [Snapcast](https://github.com/badaix/snapcast) for this, which does exactly this. It'd be an awesome feature to have!

**Comment by MayaPosch** [comment]
@PureTryOut I looked at the SnapCast implementation.I started on an implementation that should be somewhat similar. Targeting multi-room playback for v0.1, with further features imaginable later on :)

**Comment by MayaPosch** [comment]
An initial implementation of the multi-cast/multi-room playback feature has been added to the codebase. The codebase is currently rather rough after some additional refactoring, but I expect this feature to stabilise soon before the v0.1 feature freeze.

**Comment by MayaPosch** [comment]
Initial testing with two NC servers (one PC, one RPi SBC) shows the implementation to be essentially working. I'm still working out the details with the synchronisation and have implemented a potential fix that should improve this today.

As a quick overview, using the multi-cast feature requires two or more devices (remotes) running the NC server, as well as the Qt-based NymphCast Player:

- Find remotes in the player by hitting the 'refresh' button, select all of the remotes that one wishes to include in the group (multi-select using Ctrl or equivalent).
- Hit the 'connect' button at the bottom of the same tab. The remotes will configure themselves in a master/slave configuration.
- Select a track to play in the player tab. Hit play.
- The track should now play on all remote devices.

As usual, all the devices and client should be on the same network for the auto-discovery feature to work.

**Comment by PureTryOut** [comment]
I guess this issue can be closed?

**Comment by PureTryOut** [comment]
I just wanted to test this out but the connect button on the remote tab doesn't seem to do anything? :thinking:

**Comment by MayaPosch** [comment]
This feature has been tested and found to be working well enough as an experimental feature in the v0.1 release. Further development will take place in v0.2-dev. 

Please create a new ticket if issues with the current implementation are found>
