### ISSUE TITLE
confused on how to install on server

### ISSUE THREAD

**Issue by hasansultan92** [MayaPosch/NymphCast#25]
Hey guys, I hope you are doing well. I am hoping if you can explain how to even get this project installed on the raspberry pi. I am very confused as to where to start and what all do download.

**Comment by MayaPosch** [comment]
I have updated the README to hopefully make it more obvious. 

First step is to clone the project to the Raspberry Pi, then (assuming you're running current Raspbian) run `./setup.sh` in the root of the project.

Please let us know if anything else is unclear so that we can update the documentation accordingly.

**Comment by hasansultan92** [comment]
Dear Maya,
I hope you are doing well, I currently do not have access to my raspberry pi but I do have access to ssh into it. I did try to install it and ill send u the messages I have received from it. There was an error but I cannot figure out how to fix it. I tried to connect the IP address of the pi from the mobile app and I have no clue if it did connect since no prompts came and like I said I can’t physically touch  it for a couple of hours. Do u think the install went fine or is there a fatal error?


pi@raspberrypi:~/Desktop/NymphCast $ ./setup.sh
UPDATE:
PACKAGE:
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
211 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
libavcodec-dev is already the newest version (7:4.1.4-1+rpt7~deb10u1).
libavdevice-dev is already the newest version (7:4.1.4-1+rpt7~deb10u1).
libavformat-dev is already the newest version (7:4.1.4-1+rpt7~deb10u1).
libavutil-dev is already the newest version (7:4.1.4-1+rpt7~deb10u1).
libpostproc-dev is already the newest version (7:4.1.4-1+rpt7~deb10u1).
libswresample-dev is already the newest version (7:4.1.4-1+rpt7~deb10u1).
libswscale-dev is already the newest version (7:4.1.4-1+rpt7~deb10u1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libpoco-dev : Depends: libpococrypto60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocodata60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocoencodings60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocofoundation60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocojson60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocodatamysql60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocomongodb60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpoconet60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpoconetssl60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocodataodbc60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocodatasqlite60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocoredis60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocoutil60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocoxml60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: libpocozip60 (= 1.9.0-5+b1) but it is not going to be installed
               Depends: default-libmysqlclient-dev but it is not going to be installed
               Depends: libpcre3-dev but it is not going to be installed
               Depends: libsqlite3-dev but it is not going to be installed
               Depends: libssl-dev but it is not going to be installed
 libsdl2-dev : Depends: libasound2-dev but it is not going to be installed
               Depends: libdbus-1-dev but it is not going to be installed
               Depends: libegl1-mesa-dev but it is not going to be installed
               Depends: libgl1-mesa-dev but it is not going to be installed
               Depends: libgles2-mesa-dev but it is not going to be installed
               Depends: libglu1-mesa-dev but it is not going to be installed
               Depends: libibus-1.0-dev but it is not going to be installed
               Depends: libpulse-dev but it is not going to be installed
               Depends: libsndio-dev but it is not going to be installed
               Depends: libudev-dev but it is not going to be installed
               Depends: libwayland-dev but it is not going to be installed
               Depends: libx11-dev but it is not going to be installed
               Depends: libxcursor-dev but it is not going to be installed
               Depends: libxext-dev but it is not going to be installed
               Depends: libxi-dev but it is not going to be installed
               Depends: libxinerama-dev but it is not going to be installed
               Depends: libxkbcommon-dev but it is not going to be installed
               Depends: libxrandr-dev but it is not going to be installed
               Depends: libxss-dev but it is not going to be installed
               Depends: libxt-dev but it is not going to be installed
               Depends: libxv-dev but it is not going to be installed
               Depends: libxxf86vm-dev but it is not going to be installed
 libsdl2-image-dev : Depends: libsdl2-image-2.0-0 (= 2.0.4+dfsg1-1+deb10u1) but it is not going to be installed
 udev : Depends: libudev1 (= 241-7~deb10u1+rpi1) but 241-7~deb10u3+rpi1 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
Cloning into 'NymphRPC'...
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 101 (delta 12), reused 53 (delta 3), pack-reused 0
Receiving objects: 100% (101/101), 12.14 MiB | 989.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
Installing NymphRPC...
make: Entering directory '/home/pi/Desktop/NymphCast/NymphRPC'
mkdir -p lib
mkdir -p obj/static/src
mkdir -p obj/shared/src
g++ -c -o obj/static/src/nymph_listener.o src/nymph_listener.cpp -I src -g3 -std=c++11 -O0
In file included from src/nymph_listener.cpp:16:
src/nymph_listener.h:25:10: fatal error: Poco/Mutex.h: No such file or directory
 #include <Poco/Mutex.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:57: obj/static/src/nymph_listener.o] Error 1
make: Leaving directory '/home/pi/Desktop/NymphCast/NymphRPC'
cp: cannot stat 'NymphRPC/lib/libnymphrpc.a': No such file or directory
cp: cannot stat 'NymphRPC/lib/libnymphrpc.so.*': No such file or directory
chmod: cannot access '/usr/local/lib/libnymphrpc.a': No such file or directory
chmod: cannot access '/usr/lib/libnymphrpc.so*': No such file or directory
make: Entering directory '/home/pi/Desktop/NymphCast/src/server'
rm obj/sarge.o obj/config_parser.o obj/screensaver.o obj/chronotrigger.o obj/NymphCastServer.o obj/ffplay/ffplay.o obj/ffplay/sdl_renderer.o obj/ffplay/decoder.o obj/ffplay/subtitle_handler.o obj/ffplay/video_renderer.o obj/ffplay/player.o obj/ffplay/clock.o obj/ffplay/audio_renderer.o obj/ffplay/frame_queue.o obj/ffplay/packet_queue.o obj/ffplay/stream_handler.o obj/angelscript/add_on/scriptstdstring/scriptstdstring.o obj/angelscript/add_on/scriptstdstring/scriptstdstring_utils.o obj/angelscript/add_on/scriptbuilder/scriptbuilder.o obj/angelscript/add_on/scriptarray/scriptarray.o obj/angelscript/add_on/scriptdictionary/scriptdictionary.o obj/angelscript/json/jsonvalue.o obj/angelscript/json/jsonfile.o obj/ffplay/cmdutils.o
rm: cannot remove 'obj/sarge.o': No such file or directory
rm: cannot remove 'obj/config_parser.o': No such file or directory
rm: cannot remove 'obj/screensaver.o': No such file or directory
rm: cannot remove 'obj/chronotrigger.o': No such file or directory
rm: cannot remove 'obj/NymphCastServer.o': No such file or directory
rm: cannot remove 'obj/ffplay/ffplay.o': No such file or directory
rm: cannot remove 'obj/ffplay/sdl_renderer.o': No such file or directory
rm: cannot remove 'obj/ffplay/decoder.o': No such file or directory
rm: cannot remove 'obj/ffplay/subtitle_handler.o': No such file or directory
rm: cannot remove 'obj/ffplay/video_renderer.o': No such file or directory
rm: cannot remove 'obj/ffplay/player.o': No such file or directory
rm: cannot remove 'obj/ffplay/clock.o': No such file or directory
rm: cannot remove 'obj/ffplay/audio_renderer.o': No such file or directory
rm: cannot remove 'obj/ffplay/frame_queue.o': No such file or directory
rm: cannot remove 'obj/ffplay/packet_queue.o': No such file or directory
rm: cannot remove 'obj/ffplay/stream_handler.o': No such file or directory
rm: cannot remove 'obj/angelscript/add_on/scriptstdstring/scriptstdstring.o': No such file or directory
rm: cannot remove 'obj/angelscript/add_on/scriptstdstring/scriptstdstring_utils.o': No such file or directory
rm: cannot remove 'obj/angelscript/add_on/scriptbuilder/scriptbuilder.o': No such file or directory
rm: cannot remove 'obj/angelscript/add_on/scriptarray/scriptarray.o': No such file or directory
rm: cannot remove 'obj/angelscript/add_on/scriptdictionary/scriptdictionary.o': No such file or directory
rm: cannot remove 'obj/angelscript/json/jsonvalue.o': No such file or directory
rm: cannot remove 'obj/angelscript/json/jsonfile.o': No such file or directory
rm: cannot remove 'obj/ffplay/cmdutils.o': No such file or directory
make: *** [Makefile:86: clean] Error 1
make: Leaving directory '/home/pi/Desktop/NymphCast/src/server'
make: Entering directory '/home/pi/Desktop/NymphCast/src/server'
make -C angelscript/angelscript/projects/gnuc/ static
make[1]: Entering directory '/home/pi/Desktop/NymphCast/src/server/angelscript/angelscript/projects/gnuc'
mkdir -p "../../lib"
mkdir -p "obj"
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_atomic.o -c ../../source/as_atomic.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_builder.o -c ../../source/as_builder.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_bytecode.o -c ../../source/as_bytecode.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_callfunc.o -c ../../source/as_callfunc.cpp
../../source/as_callfunc.cpp: In function ‘int DetectCallingConvention(bool, const asSFuncPtr&, int, void*, asSSystemFunctionInterface*)’:
../../source/as_callfunc.cpp:58:56: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct asSSystemFunctionInterface’ with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
  memset(internal, 0, sizeof(asSSystemFunctionInterface));
                                                        ^
In file included from ../../source/as_callfunc.cpp:41:
../../source/as_callfunc.h:98:8: note: ‘struct asSSystemFunctionInterface’ declared here
 struct asSSystemFunctionInterface
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_callfunc_arm.o -c ../../source/as_callfunc_arm.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_callfunc_mips.o -c ../../source/as_callfunc_mips.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_callfunc_ppc.o -c ../../source/as_callfunc_ppc.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_callfunc_ppc_64.o -c ../../source/as_callfunc_ppc_64.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_callfunc_sh4.o -c ../../source/as_callfunc_sh4.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_callfunc_x86.o -c ../../source/as_callfunc_x86.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_callfunc_x64_gcc.o -c ../../source/as_callfunc_x64_gcc.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_callfunc_x64_mingw.o -c ../../source/as_callfunc_x64_mingw.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_compiler.o -c ../../source/as_compiler.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_context.o -c ../../source/as_context.cpp
../../source/as_context.cpp: In member function ‘void asCContext::DetermineLiveObjects(asCArray<int>&, asUINT)’:
../../source/as_context.cpp:4771:11: warning: enumeration value ‘asOBJ_VARDECL’ not handled in switch [-Wswitch]
     switch( func->scriptData->objVariableInfo[n].option )
           ^
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_configgroup.o -c ../../source/as_configgroup.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_datatype.o -c ../../source/as_datatype.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_generic.o -c ../../source/as_generic.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_gc.o -c ../../source/as_gc.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_globalproperty.o -c ../../source/as_globalproperty.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_memory.o -c ../../source/as_memory.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_module.o -c ../../source/as_module.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_objecttype.o -c ../../source/as_objecttype.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_outputbuffer.o -c ../../source/as_outputbuffer.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_parser.o -c ../../source/as_parser.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_restore.o -c ../../source/as_restore.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_scriptcode.o -c ../../source/as_scriptcode.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_scriptengine.o -c ../../source/as_scriptengine.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_scriptfunction.o -c ../../source/as_scriptfunction.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_scriptnode.o -c ../../source/as_scriptnode.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_scriptobject.o -c ../../source/as_scriptobject.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_string.o -c ../../source/as_string.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_string_util.o -c ../../source/as_string_util.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_thread.o -c ../../source/as_thread.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_tokenizer.o -c ../../source/as_tokenizer.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_typeinfo.o -c ../../source/as_typeinfo.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_variablescope.o -c ../../source/as_variablescope.cpp
g++ -Wall -fPIC -fno-strict-aliasing -o obj/as_callfunc_arm_gcc.o -c ../../source/as_callfunc_arm_gcc.S
ar r "../../lib"/libangelscript.a obj/as_atomic.o obj/as_builder.o obj/as_bytecode.o obj/as_callfunc.o obj/as_callfunc_arm.o obj/as_callfunc_mips.o obj/as_callfunc_ppc.o obj/as_callfunc_ppc_64.o obj/as_callfunc_sh4.o obj/as_callfunc_x86.o obj/as_callfunc_x64_gcc.o obj/as_callfunc_x64_mingw.o obj/as_compiler.o obj/as_context.o obj/as_configgroup.o obj/as_datatype.o obj/as_generic.o obj/as_gc.o obj/as_globalproperty.o obj/as_memory.o obj/as_module.o obj/as_objecttype.o obj/as_outputbuffer.o obj/as_parser.o obj/as_restore.o obj/as_scriptcode.o obj/as_scriptengine.o obj/as_scriptfunction.o obj/as_scriptnode.o obj/as_scriptobject.o obj/as_string.o obj/as_string_util.o obj/as_thread.o obj/as_tokenizer.o obj/as_typeinfo.o obj/as_variablescope.o obj/as_callfunc_arm_gcc.o
ar: creating ../../lib/libangelscript.a
ranlib "../../lib"/libangelscript.a
make[1]: Leaving directory '/home/pi/Desktop/NymphCast/src/server/angelscript/angelscript/projects/gnuc'
mkdir -p obj/ffplay
mkdir -p obj/angelscript/add_on/scriptstdstring
mkdir -p obj/angelscript/add_on/scriptbuilder
mkdir -p obj/angelscript/add_on/scriptarray
mkdir -p obj/angelscript/add_on/scriptdictionary
mkdir -p obj/angelscript/json
mkdir -p bin
g++ -c -o obj/sarge.o sarge.cpp -ffunction-sections -fdata-sections -g3 -O0 -I . -I ffplay -I angelscript/angelscript/include -I angelscript/add_on -I angelscript/json `sdl2-config --cflags` -std=c++17
/bin/sh: 1: sdl2-config: not found
g++ -c -o obj/config_parser.o config_parser.cpp -ffunction-sections -fdata-sections -g3 -O0 -I . -I ffplay -I angelscript/angelscript/include -I angelscript/add_on -I angelscript/json `sdl2-config --cflags` -std=c++17
/bin/sh: 1: sdl2-config: not found
In file included from config_parser.cpp:17:
config_parser.h:25:10: fatal error: Poco/Util/IniFileConfiguration.h: No such file or directory
 #include <Poco/Util/IniFileConfiguration.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:75: obj/config_parser.o] Error 1
make: Leaving directory '/home/pi/Desktop/NymphCast/src/server'
pi@raspberrypi:~/Desktop/NymphCast $ apt-get --install
E: Command line option --install is not understood in combination with the other options
pi@raspberrypi:~/Desktop/NymphCast $ apt --fix-broken install
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
pi@raspberrypi:~/Desktop/NymphCast $ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  fonts-noto-core fonts-noto-hinted fonts-noto-ui-core fonts-roboto-hinted
  fonts-roboto-unhinted kodi-bin kodi-data kodi-repository-kodi
  kodi-visualization-spectrum libcec4 libcrossguid0 libjs-iscroll liblzo2-2
  libmariadb3 libmicrohttpd12 libp8-platform2 libpcrecpp0v5 libtinyxml2.6.2v5
  libyajl2 mariadb-common mysql-common
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  udev
The following packages will be upgraded:
  udev
1 upgraded, 0 newly installed, 0 to remove and 210 not upgraded.
1 not fully installed or removed.
Need to get 0 B/1,252 kB of archives.
After this operation, 1,024 B of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg-deb (subprocess): cannot copy archive member from '/var/cache/apt/archives/udev_241-7~deb10u3+rpi1_armhf.deb' to decompressor pipe: failed to write (Broken pipe)
Reading changelogs... Done
(Reading database ... 98205 files and directories currently installed.)
Preparing to unpack .../udev_241-7~deb10u3+rpi1_armhf.deb ...
Unpacking udev (241-7~deb10u3+rpi1) over (241-7~deb10u1+rpi1) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/udev_241-7~deb10u3+rpi1_armhf.deb (--unpack):
 cannot copy extracted data for './lib/udev/hwdb.d/20-usb-vendor-model.hwdb' to '/lib/udev/hwdb.d/20-usb-vendor-model.hwdb.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 /var/cache/apt/archives/udev_241-7~deb10u3+rpi1_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)




Apologies if it looks like a mess. Thank you so much for ure help!!
Regards,
Hasan Sultan



On Mar 22, 2020, at 2:31 PM, Maya Posch <notifications@github.com<mailto:notifications@github.com>> wrote:



I have updated the README to hopefully make it more obvious.

First step is to clone the project to the Raspberry Pi, then (assuming you're running current Raspbian) run ./setup.sh in the root of the project.

Please let us know if anything else is unclear so that we can update the documentation accordingly.

**Comment by MayaPosch** [comment]
Looks like a number of dependencies cannot be installed.

>  udev : Depends: libudev1 (= 241-7~deb10u1+rpi1) but 241-7~deb10u3+rpi1 is to be installed E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

That looks very much like your particular installation of Raspbian has some broken packages that prevent apt-get from installing new packages.
