### ISSUE TITLE
Possible memory leak that impact on Xorg

### ISSUE THREAD

**Issue by Gotrek77** [MayaPosch/NymphCast#34]
Hi,
I notice that at every image change of wallpaper, the memory size occupied by Xorg grows. This after some time passed, impacts stability, because the MemoryOOMKiller is triggered by the kernel, and raspberry is rebooted.

**Comment by MayaPosch** [comment]
Hello and thank you for trying out NymphCast :)

Does this issue occur for you with the current version (latest commit) of NymphCast?

I have tested to see whether I can reproduce this issue with Raspbian Buster on a Raspberry Pi 3B, but without `top` reporting any increase in memory use by either Xorg or NymphCast server while it's running in screensaver mode.

Testing with Valgrind's Memcheck tool under Raspbian Buster x86 also shows no memory leaks in NymphCast.

It would be great if you could provide more details about this issue.

**Comment by Gotrek77** [comment]
Hello!
I'm sorry for my late reply.
I don't know why this happens, but I can explain more details about my use case.
I want to use NymphCast in this way:
- I installed on my rpi4 the Balena OS 2.48.0+rev1
- I created a docker-compose.yml to create 2 services:
   - one for Xorg
   - one with NymphCast
I want to separate all single services as a container.
If you want to try:
https://gitlab.com/giuseppe.patane/nymphcastdockerrpi4

Just a note: I'm trying to disabling oom_killer to see if I can mitigate the full reboot of the system, so probably in docker-compose.yml you need to comment:
oom_score_adj: -1000
oom_kill_disable: true
to reset these settings

I hope you like it!
Best
Giuseppe

**Comment by MayaPosch** [comment]
Hello @Gotrek77, I wanted to check whether you are still having this issue?

I have made some changes to how SDL is used, which may have affected your use case.

Thanks!
