### ISSUE TITLE
Build failure on armv7

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphCast#35]
0.1-alpha2 fails to build on armv7 (again :cry:).

Seems it's some assembly thing again, you can see the build log [here](https://gitlab.alpinelinux.org/PureTryOut/aports/-/jobs/113405/raw).

**Comment by MayaPosch** [comment]
The 0.1-alpha2 release was a while ago already... seems like it did not have the fix in the AngelScript Makefile in it yet.

I created a new (v0.1-alpha3) release point that also has a lot more new features in it: https://github.com/MayaPosch/NymphCast/releases/tag/v0.1-alpha3

**Comment by PureTryOut** [comment]
Yup seems it has been fixed in the meantime, it compiles fine now, thanks!
