### ISSUE TITLE
Compilation issue "conflicting declaration 'const uint32_t nymph_seek_event'"

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphCast#4]
```
NymphCastServer.cpp:223:16: error: conflicting declaration 'const uint32_t nymph_seek_event'
  223 | const uint32_t nymph_seek_event = SDL_RegisterEvents(1);
      |                ^~~~~~~~~~~~~~~~
In file included from NymphCastServer.cpp:31:
ffplay/types.h:449:17: note: previous declaration as 'uint32_t nymph_seek_event'
  449 | extern uint32_t nymph_seek_event;
      |                 ^~~~~~~~~~~~~~~~
```

This happens on Alpine Linux with Musl 1.1.24.

**Comment by MayaPosch** [comment]
Reproduced it under Windows with MSYS2 & GCC 9.2. Fixed the wrong type declaration in the header file. Please verify that it compiles now.

**Comment by PureTryOut** [comment]
Yup, it goes through now, thanks for the quick response!

Next issue: for some reason the linker can't find nymphrpc and PocoNetSSL. Doesn't nymphrpc need at least a pkgconfig file?

```
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lnymphrpc
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lPocoNetSSL
```

**Comment by MayaPosch** [comment]
As long as the NymphRPC library (.a) is found on the path it should link. Did you compile NymphRPC as a library (make lib) and copy the library into a standard search location like /usr/local/lib?

PocoNetSSL might be because the Poco version is too old.. PocoNetSSL got added later on if I remember correctly.

**Comment by PureTryOut** [comment]
I have the library installed as `/usr/lib/libnymphrpc.a` (would be nice if some dynamic library was possible here), is that not the right location?

As for Poco, Alpine has 1.10.1 packaged, which according to the site is the newest version.

**Comment by MayaPosch** [comment]
Odd that it won't find libnymphrpc then =/ I figure that should work.

As for libPocoNetSSL, I assume it is present?

I'll try to reproduce this issue tomorrow in a VM.

**Comment by PureTryOut** [comment]
Woops, fixed the libnymphrpc problem. I forgot the package splitting meant I have to install the `nymphrpc-static` subpackage as well :man_facepalming: 

I'm looking into Poco now, it seems Alpine currently ships a really minimal build of it. I'm going to switch it from autotools to CMake and make it a more fully featured build, should fix the rest of it.

Thanks for your help so far! Only problems left seem to be packaging problems but nothing nymphcast specific :wink:
