### ISSUE TITLE
Launch on Startup

### ISSUE THREAD

**Issue by Arndorferd** [MayaPosch/NymphCast#41]
There may be ways to hack this but a launch on startup feature would be nice for use with raspberry pi as a chromecast alternative. I noticed that in order for it to come fullscreen I also needed to click for it to go fullscreen, the video starts out in a small corner of the server and becomes fullscreen after click. Some kind of optional automation so it starts full screen on startup of pi or at least in startup of server or video would be necessary for any kind of convenience in this regard.

**Comment by MayaPosch** [comment]
The SDL code in NymphCast Server has been refactored significantly over the past months. I have noticed some issues with full-screen mode as well, though most issues should be resolved by now. 

Fixing the remaining issues with full-screen are definitely a priority before Beta testing starts. Exact steps to reproduce encountered issues would be most welcome here.

**Comment by PureTryOut** [comment]
At least with alpha 0.4 the NymphCast server starts up in fullscreen by default. As for starting it by default I just use the provided init script, in my case `rc-update add nymphcast`. Then it'll autolaunch after a reboot.

**Comment by PureTryOut** [comment]
I've recently taken an interest in running NymphCast on [Plasma Bigscreen](https://plasma-bigscreen.org) installations as well and the init script method wasn't good enough/not what I wanted there. For a device that's purely going to be used as a Chromecast-like device an init script does the job well, but for devices that want to do more than just casting it's good to have the NymphCast server run as the same user as the system in use.

For that purpose I just created a .desktop file which I've put in `/etc/xdg/autostart`:

```
[Desktop Entry]
Version=1.0
Name=Nymphcast
Comment=Start Nymphcast
Exec=/usr/bin/nymphcast_server -c /etc/nymphcast/nymphcast_video_config.ini -a /usr/share/nymphcast/apps
Terminal=false
Type=Application
X-KDE-autostart-phase=2
```

On systemd systems I would recommend looking into `systemctl --user` instead, but you probably get the idea.

**Comment by MayaPosch** [comment]
The installation routine for the systemd unit file provided with NC Server has been changed to run as a (global) user service rather than as a system (root-level) service. This offers the benefits of not using (risky & unneeded) root permissions, and enables the use of graphical content with the same environment and permissions as the currently logged in user.

This has been successfully  tested on Manjaro Linux. 

For any issues that may still exist with this functionality, please open a new ticket.
