### ISSUE TITLE
Instruction Clarification

### ISSUE THREAD

**Issue by Arndorferd** [MayaPosch/NymphCast#42]
In Rasbian the bin folder the server ends up in /usr/local/bin, im not sure if that's different in different linux versions, but there's also a /bin/ and /local/bin/ in Rasbian and at first ,I thought that the bin might have been created in the project directory, had to look at where everything was built into during make, the instructions just say to go to bin/ without explanation of where bin/ is.

**Comment by MayaPosch** [comment]
The `bin/` in the instructions refer to the folder that is created in the `src/server/` folder during compilation. Using `make install` copies the files in that folder to their final destinations in the filesystem.
