### ISSUE TITLE
Allow custom apps directory location

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphCast#5]
Since I'm packaging this for Alpine Linux, I'm not following the current file system structure this application expects.

I install the `nymphcast_server` binary to `/usr/bin/nymphcast_server`, the config files (`src/server/*.ini`) to `/etc/nymphcast` and apps (`src/server/apps`) to `/usr/share/nymphcast/apps`.

The binary and config files are fine, I just point my (so-far custom) init file to the right binary, and provide the config file with the `-c` argument. However, I see no current way to specify the location of the apps directory.

Is there an argument I can pass to the binary which would do this? Btw, supporting `-h` and/or `--help` would be nice :wink:

**Comment by MayaPosch** [comment]
The only expectation of the NymphCast server currently is that there's an /apps folder in the same folder as the NymphCast binary. I haven't made this configurable yet, but that's a relatively minor change.

I'll add this as an option along with the `-h` & `--help' options :)

**Comment by PureTryOut** [comment]
Thanks! Now I think about it, the wallpapers should also be installed into `/usr/share/nympchast` somewhere, probalby a `wallpapers` subdirectory. Could that be made configurable as well? Maybe a general `--data` switch which in which it then checks for the `wallpapers` and `apps` subdirectories?

**Comment by PureTryOut** [comment]
A question raised by @MartijnBraam:
With a Chromecast, applications and wallpapers are set from the remote device (phone, tablet, etc). Meaning the the `apps` and `wallpapers` directories are written too by the server when uploaded. Is this the case with Nymphcast as well? If so, I would have to install those directories to `/srv` instead.

**Comment by MayaPosch** [comment]
It was my understanding that on a ChromeCast the apps and wallpapers are loaded from a remote webserver, as specified in JSON files on the ChromeCast dongle, though one can define custom wallapers as well.

Currently with NymphCast all apps are either local, or are loaded from a remote webserver, as specified in the `apps.ini` file in the `src/server/apps/` folder. Wallpapers are currently kept solely on the local filesystem.

**Comment by MayaPosch** [comment]
I have implemented a --help, --apps and --wallpapers option (untested). Of these the wallpapers option is currently not functional yet, but feel free to give it a try with the rest :)

**Comment by PureTryOut** [comment]
Awesome, that works, thanks! I [submitted the package to Alpine](https://gitlab.alpinelinux.org/alpine/aports/merge_requests/5133)!
