### ISSUE TITLE
Player repeats media even when repeat checkbox isn't checked

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphCast#51]
Checking the checkbox seems to make no difference either. It just plays the entire playlist and then repeats it no matter what I do, I have to manually click the stop button to get it to stop.

**Comment by MayaPosch** [comment]
Sorry about that, the checkbox that enables single play is the 'Single' checkbox. I have made this enabled by default.

The NC Player UI still needs a bit more work to make such features obvious. Any feedback on UX improvements are always welcome :)

**Comment by PureTryOut** [comment]
Well yes I get that the single checkbox does that, but that's not what I meant. With "single" I assume just a single file will be played and it'll be over. When that is unchecked (and the repeat checkbox isn't checked either) then I expect the full list to be played once. If both single and repeat are checked I expect the single file to be repeated indefinitely, and when single is unchecked but repeat is checked I expect the full list to be played and then repeated indefinitely.

**Comment by MayaPosch** [comment]
Thank you for the explanation. 

It appears that the state of the 'Repeat' checkbox wasn't being taken into account yet. My apologies for that. I have updated the code.

**Comment by PureTryOut** [comment]
Yup it now does exactly what I expect it too, thanks!
