### ISSUE TITLE
Connect button in NymphCastPlayer Remote tab doesn't do anything

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphCast#53]
This makes it quite hard to test #23 :thinking:

**Comment by MayaPosch** [comment]
Sorry about that. The creating of groups is intended to be performed via a new dialogue (accessible via the currently helpfully labelled '...' button). The old grouping of remotes via the Remotes tab has apparently already removed during the Player code refactoring a few months back.

I'm currently working on implementing the new Remotes & Groups management dialogue, along with persistence for the thus created groups and further UI options in the Player. I expect that this will ready later this week.

**Comment by MayaPosch** [comment]
The changes and additions to the Player have been made and have been tested under Manjaro in so far as that the player starts up and doesn't catch on fire :)

Creating groups in the new dialogue (accessible via the "..." button next to each remotes combobox) has to be tested, as does persisting groups and selecting a group for multicasting. 

I'll likely be testing this over the weekend, but feel free to poke at it too :)

**Comment by MayaPosch** [comment]
Considering this feature implemented. Feel free to open a new issue if new issues are found.
