### ISSUE TITLE
There is a video demo?

### ISSUE THREAD

**Issue by paulocoutinhox** [MayaPosch/NymphCast#56]
Hi,

There is a video demo?

Thanks.

**Comment by MayaPosch** [comment]
Videos of setting up and using NymphCast are currently being produced. What would your expectations with these videos be? It could be incorporated into these videos.

Thank you.

**Comment by paulo-coutinho** [comment]
Hi,

Only use cases, configurations and working with it on mobile (ios and android) and html5.

Thanks.

**Comment by MayaPosch** [comment]
Thank you, we'll take it under consideration.

**Comment by kojid0** [comment]
Adding to this, I would also like to see the use cases. Additionally, a step-by-step guide for setting things up from scratch. But this can also be done via text.

**Comment by MayaPosch** [comment]
> Adding to this, I would also like to see the use cases. Additionally, a step-by-step guide for setting things up from scratch. But this can also be done via text.

The main README lists the use cases, and links to detailed setup guides for each usage scenarios. E.g. for NymphCast Audio: https://github.com/MayaPosch/NymphCast/blob/master/doc/nymphcast_audio_setup_guide.md

Feedback on making documentation better is of course always welcome :)
