### ISSUE TITLE
Build failure: no matching function for call to 'NymphMethod::NymphMethod

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphCast#57]
I'm assuming this means NymphCast requires git master of nymphrpc rather than 0.1_alpha0. If that is the case, could Nymphrpc please get a new release?

```
NymphCastServer.cpp:1971:83: error: no matching function for call to 'NymphMethod::NymphMethod(const char [9], std::vector<NymphTypes>&, NymphTypes, NymphMessage* (&)(int, NymphMessage*, void*))'
 1971 |         NymphMethod appListFunction("app_list", parameters, NYMPH_STRING, app_list);
      |                                                                                   ^
In file included from /usr/include/nymph/remote_server.h:26,
                 from /usr/include/nymph/nymph.h:19,
                 from NymphCastServer.cpp:53:
```

**Comment by PureTryOut** [comment]
And yup, it compiles fine with nymphrpc from git master. Please either fix compilation in Nymphcast with an older nymphrpc or make a new release of nymphrpc :sweat_smile:

**Comment by MayaPosch** [comment]
I have just created new pre-release tags for the NymphRPC and libNymphCast projects: v0.1-alpha1 and v0.1-beta0 respectively.

As you noticed, the previous tagged releases were somewhat outdated :)

**Comment by PureTryOut** [comment]
Yup, I noticed :wink:  Thanks, it was in fact an outdated libnymphcast that was the issue. Thanks for tagging it!
