### ISSUE TITLE
Unable to install Android client

### ISSUE THREAD

**Issue by bellpeterm** [MayaPosch/NymphCast#58]
When attempting to install the beta package (nymphcast_player_v0.1-beta0.apk), I get the following message:

"There was a problem parsing the package."

Device Model: Pixel 4
Android Version: 12
Build Number: SQ1A.211205.008

Installing via `adb shell`, I get the following:

```Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1802163965.tmp/base.apk (at Binary XML file line #40): org.qtproject.qt5.android.bindings.QtActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]```

**Comment by MayaPosch** [comment]
Thank you for reporting this issue. It appears that starting with Android 12 (API 31) it is now required to explicitly specify whether intents are to be exported or not. I have made this change to the Android Manifest file and built a new APK.

See `nymphcast_player_v0.1-rc0.apk` on the release page: https://github.com/MayaPosch/NymphCast/releases/tag/v0.1-rc0

I have tested installation on a virtual Android device running Android 12. Please let me know whether it works for you now as well.

**Comment by bellpeterm** [comment]
The new package installed and runs great.  Thanks!
