### ISSUE TITLE
Player: video seeking not working

### ISSUE THREAD

**Issue by mapl** [MayaPosch/NymphCast#64]
I have noticed that seeking / fast forwarding a video in progress just doesn't work. Is this a known issue?

**Comment by MayaPosch** [comment]
The seek feature was indeed not working. I have implemented a number of fixes that should at least enable the feature.

There may still be some synchronisation issues for the new playback position in a file.

**Comment by PureTryOut** [comment]
Hey is this issue resolved? It's listed as part of the v0.1 milestone but 0.1 has already been released. Can this be closed?

**Comment by MayaPosch** [comment]
I expect that it's resolved now since I have not seen the issue occur on my side, nor heard of it from other testers.

Closing it as resolved.
