### ISSUE TITLE
SDK: where does error.h come from?

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphCast#7]
I'm trying to build the client_lib, but it seems `error.h` as required by `zeroconf-detail.hpp` on line 18 is not present on my system. I'm however unsure which package to retrieve it from.

**Comment by MayaPosch** [comment]
It appears to be a GNU extension header: http://man7.org/linux/man-pages/man3/error_at_line.3.html

None of its functions appear to be used in the source, though. Maybe it'll work without the header?

**Comment by PureTryOut** [comment]
Huh yeah that works, I'll make a PR!
