### ISSUE TITLE
Need help getting started 

### ISSUE THREAD

**Issue by Ryan5374** [MayaPosch/NymphCast#74]
This is probably a dumb question, but I ran the .sh file to install the binary on Ubuntu, but now I don't know how to start the program. I read the "./nymphcast_server -c nymphcast_audio_config.ini" but could not find the ./nymphcast_server folder.

**Comment by MayaPosch** [comment]
Which .sh file did you run? If `setup.sh` the entire installation and setup should have been automated.

See the server installation instructions here: https://github.com/MayaPosch/NymphCast/blob/master/doc/building_nymphcast_server.md

**Comment by Ryan5374** [comment]
I ran setup.sh. I just don't know how to get the program running after installing it with that script.

**Comment by MayaPosch** [comment]
After running `setup.sh` the server will have been compiled with the binary placed in `src/server/bin/<arch>/`. 

You can run the server after this either by navigating to the `src/server` folder and executing e.g. `./bin/<arch>/nymphcast_server -c nymphcast_audio_config.ini` for an audio-only configuration.

You can also install the server with the `install_linux.sh` script. This will copy the server's files to system folders and optionally allows you to install it as a system service.

I hope this helps.

**Comment by Ryan5374** [comment]
Thank you for the help :)

**Comment by ayushbharadva** [comment]
I am also having some issues with project startup, i have a windows system. confused about running the NymphCast server in my system.
