### ISSUE TITLE
Raspberry Pi Server: Audio works through the receiver, but doesn't output video

### ISSUE THREAD

**Issue by jmillerv** [MayaPosch/NymphCast#85]
I've gotten NymphCast running on a machine. I have it plugged in via HDMI to my television. I can successfully cast from my phone to the television; however, only audio comes through. Additionally, I can't get audio or video from a YouTube URL, but can get it from a file on my phone. 

Is there a step where I need to enable something so that NymphCast outputs to the HDMI instead of the basic Pi desktop? I haven't tried diving into those settings yet. 

The only error I'm seeing is `error: XDG_RUNTIME_DIR is invalid or not set in the environment.`

Hardware 

Rasbperry Pi Zero W

Operating System 

```
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```
Startup & Logs 

```
systemctl status nymphcast.service
● nymphcast.service - NymphCast audio/video casting server
     Loaded: loaded (/etc/systemd/system/nymphcast.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-03-26 11:21:23 EDT; 6min ago
   Main PID: 365 (nymphcast_serve)
      Tasks: 10 (limit: 375)
        CPU: 17.064s
     CGroup: /system.slice/nymphcast.service
             └─365 /usr/local/bin/nymphcast_server -c /usr/local/etc/nymphcast/nymphcast_screensaver_config.ini -a /usr/local/share/nymphcast/apps -w /usr/local/share/nymphcast/wallpapers

Mar 26 11:22:17 raspberrypi nymphcast_server[365]: error: XDG_RUNTIME_DIR is invalid or not set in the environment.
Mar 26 11:22:18 raspberrypi nymphcast_server[365]: Creating window with dimensions 1024x768.
Mar 26 11:22:57 raspberrypi nymphcast_server[365]: Registering methods...
Mar 26 11:22:57 raspberrypi nymphcast_server[365]: Found 2 wallpapers.
Mar 26 11:22:57 raspberrypi nymphcast_server[365]: Changing image to /usr/local/share/nymphcast/wallpapers/forest_brook.jpg
Mar 26 11:23:12 raspberrypi nymphcast_server[365]: Changing image to /usr/local/share/nymphcast/wallpapers/green.jpg
Mar 26 11:27:15 raspberrypi nymphcast_server[365]: Changing image to /usr/local/share/nymphcast/wallpapers/forest_brook.jpg
Mar 26 11:27:30 raspberrypi nymphcast_server[365]: Changing image to /usr/local/share/nymphcast/wallpapers/green.jpg
Mar 26 11:27:45 raspberrypi nymphcast_server[365]: Changing image to /usr/local/share/nymphcast/wallpapers/forest_brook.jpg
Mar 26 11:28:00 raspberrypi nymphcast_server[365]: Changing image to /usr/local/share/nymphcast/wallpapers/green.jpg

```

**Comment by MayaPosch** [comment]
The missing `XDG_RUNTIME_DIR` in the environment seems to occur with both running the service as root and as specific users. I remember struggling with it a few years back on the RPi while setting up a video config NCS instance. Back then I think I resolved it, but I'll have to look at the details and set up a fresh RPi test system.

As a workaround it should be possible to set the target user as your own user account in the `nymphcast.service` file.

**Comment by jmillerv** [comment]
I don't think I updated my `nymphcast.service` file properly, because nothing seemed to change. 

Based on mentioning the different accounts, I stopped the service and ran the binary from the user account. The error disappears, but I can still only receive audio. 

  This file is playing from my Windows PC instead of my phone and it also only sends audio. 

```
./bin/nymphcast_server -c nymphcast_video_config.ini 
Detected Host Little Endian.
Setting app folder to default location.
Setting wallpapers folder to default location.
Setting resource folder to default location.
Adding app: HelloCast
Adding app: SoundCloud
Initialising server...
Dispatcher: Setting max pool size to 10 workers.
Dispatcher: Setting max pool size to 10 workers.
Registering methods...
Creating window with dimensions 1024x768.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '':   0KB sq=    0B f=0/0     0 aq=    0KB vq=    0KB sq=    0B f=0/0   
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:00.000000Z
    encoder         : Lavf53.24.2
  Duration: 00:00:13.50, start: 0.000000, bitrate: 1248 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 862 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 381 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler
Finding audio stream...
Found audio stream: 1.
A: 1, V: 0, S: -1
SetDuration. 13
Goto 'fail'. Exiting main loop... 48KB vq= 1173KB sq=    0B f=0/0   
SetDuration. 0
Closing audio stream component...
Closing audio device...
Terminating player...d=  28 aq=    0KB vq= 1166KB sq=    0B f=0/0   
```

**Comment by MayaPosch** [comment]
Thank you for that information, it's strange that it still doesn't work even with the XDG environment variable set. I'll take a look at the issue later this week and hopefully come up with some clues.

**Comment by jmillerv** [comment]
If I discover anything else, I'll let you know. My endeavor down this path started because I spent hours looking for an old Chromecast in my house and couldn't find it. I then went to the well-organized drawer of single board computers and thought, "surely you can just turn one of these into a Chromecast." I didn't realize that Google had such a monopoly on streaming data from one device to another. 

Thank you for your efforts to make that not the case!

**Comment by jmillerv** [comment]
I got video throughput, but I'm not sure that the Zero W has the bandwidth needed to stream data. 


**Solution**: The final step here is that I need to disable the raspbery pi OS GUI, and then I can get data. Going to close this one.

**Comment by MayaPosch** [comment]
Interesting finding. I'll see whether I can use this factoid to make the setup procedure for NymphCast a bit more automated, or worst case add it as a note to the setup instructions :)

As for playing back video on a Raspberry Pi Zero W, a big limitation with the RPi SBCs is the poor support for video decoding in hardware. There are two proprietary Broadcom APIs (MMAL & OpenMAX) that are somewhat-ish supported by many applications and software, including ffmpeg (used by NymphCast). When not used, this means that video decoding is done on the CPU so that only e.g. SD MPEG-2 or such plays back somewhat okay-ish on lower-end RPi boards.

Theoretically the RPi Zero boards can do 1080p h.264 decoding, but I'll need to take another look at the HW acceleration topic for ffmpeg to make sure MMAL decoding is actually used by default. Thank you for reminding me of this topic, now I have an excuse to dig out those boards again :)

**Comment by jmillerv** [comment]
I dug out a Raspberry Pi 3 because it's beefier and the video is streaming at a respectable speed, but now I don't have audio :( Going to determine if there's something wrong with my board/OS before knocking on the issue door.  If I find anything new, I'll open an issue. 

Good to know about the RBi SBCs and poor video decoding. I've mostly only used them for random server projects where video rendering wasn't the goal.
