### ISSUE TITLE
Calling media status callback failed: Provided handle was not found

### ISSUE THREAD

**Issue by jmillerv** [MayaPosch/NymphCast#86]
While troubleshooting audio connection on a Raspberry Pi 3, I got the following error at the end of a video. Which causes the video to freeze-frame on the display device. This doesn't happen in `screensaver` mode, just video mode. 

video mode error:

```
EOF is 1A-V: -0.001 fd=   0 aq=    9KB vq=   25KB sq=    0B f=0/0   
EOF is 1
Goto 'fail'. Exiting main loop...
SetDuration. 0
Closing audio stream component...
Closing audio device...
Terminating player...
2 - 923.1	NymphCastServer	445	Calling media stop callback failed: Provided handle was not found.		- NymphCastServer.cpp
2 - 923.1	NymphCastServer	372	Calling media status callback failed: Provided handle was not found.		- NymphCastServer.cpp

```

Hardware 

Raspberry PI 3 

OS

```
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

Config

`/bin/nymphcast_server -c nymphcast_video_config.ini`

**Comment by MayaPosch** [comment]
Thank you for your report. 

Can you tell me whether the error is reproducible or that it only occurred once?
