### ISSUE TITLE
uninstall?

### ISSUE THREAD

**Issue by x4dr** [MayaPosch/NymphCast#89]
uhm i ran the setup and it installed ... now i don't want it any more, is there any way to uninstall it from my system?

**Comment by MayaPosch** [comment]
Which installation method did you use, and which operating system? 

On Windows an uninstaller is provided with the binary distribution, on Linux and other platforms the files can be deleted by hand (under `/usr/local/`). I can provide an uninstall option for Linux etc. if that's helpful.

**Comment by MayaPosch** [comment]
An uninstall script has been provided for Linux: `uninstall_linux.sh`. Please open a new issue if there are any remaining issues.
