### ISSUE TITLE
Overriding CFLAGS, CPPFLAGS...

### ISSUE THREAD

**Issue by meator** [MayaPosch/NymphCast#90]
Hello. I am a packager and I've been thinking about packaging NymphCast for Void Linux and possibly for Nix (because this looks like a really cool project and I want to make it more accessible). Packaging systems often need to override `CFLAGS`, `CXXFLAGS`/`CPPFLAGS`, `LDFLAGS` and possibly more. The current `Makefile` system doesn't provide an easy way to do so.

I have read [the server Makefile](https://github.com/MayaPosch/NymphCast/blob/v0.1/src/server/Makefile) and have noticed `$PLATFORM_FLAGS`. It can (I believe) be used to provide custom compiler flags. This approach has several disadvantages:

1) `CFLAGS` and `CPPFLAGS` accept the same `$PLATFORM_FLAGS`, there is no way to set different flags for C and for C++
2) this approach deviates from the "standard" way of overriding compiler variables; the standard way is described [in the GNU Make manual](https://www.gnu.org/software/make/manual/make.html#Command-Variables)

   This approach (letting environment defined `CFLAGS`, `CXXFLAGS`... be propagated to makefiles) is more widespread and simpler to use (in my opinion). I believe that adopting this strategy could be beneficial.

Also, `$PLATFORM_FLAGS` is not standard, so it might be worth documenting it in [Building From Source](https://github.com/MayaPosch/NymphCast/blob/master/README.md#id-bfs) so that people who need to provide custom compiler arguments wouldn't have to study the Makefile.

---

As a package maintainer, I dislike seeing Makefiles in projects I'd like to maintain. It is very difficult to write a Makefile correctly (because people often do not know Makefile best practices) and it is easy to write a Makefile in a non-portable way. When writing Makefiles, many often do not take into account "edge cases" like providing a custom `$DESTDIR`, cross compiling, using custom compiler or flags, different system configurations etc. All of these are very important for packaging by the way. I personally believe that Makefiles are an inappropriate build system for medium to large projects.

NymphCast seems to be using several build systems: mostly GNU Make, NMake and seldomly CMake. High level build systems such as CMake or Meson should be capable of building projects on both Linux and Windows based OSes.

It might be worth considering a different build system (like Meson). Build systems such as Meson can provide better IDE integration with `compile_commands.json`, more descriptive error messages (I personally believe that build systems shouldn't be primarily optimized for performance or portability, but for _debuggability_), standardized ways to override the build environment (useful for specifying custom flags, for cross compiling and for exe wrappers, which can be useful for running cross compiled Windows executables on Linux through Wine to give an example) and better & more concise syntax. Make is a very "low level" build system, which has its strengths and weaknesses.

I understand that improving the build system isn't likely a priority for NymphCast now, but it might be worth considering it. If there's interest, I'm willing to contribute Meson build definition files.

**Comment by MayaPosch** [comment]
Hello,

Thank you for your interest in NymphCast. Thanks for pointing out the redundant use of `PLATFORM_FLAGS` in the Makefile for the C and C++ compiler flags. I have corrected both instances so that now `CFLAGS` and `CXXFLAGS` can be passed to make to override any flags as needed. This was behaviour that was previously unneeded and therefore untested. My apologies for that.

Please open a new ticket if there are any further issues.

**Comment by meator** [comment]
Thanks for fixing the makefile!

As for the second part of my issue, would you be interested in my offer to add Meson to your project?

**Comment by MayaPosch** [comment]
Thanks for the offer, but at this point there are no plans to support build systems other than Make.
